# Generated by Django 2.0.6 on 2018-06-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_employee_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_message',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='message_shift',
            field=models.IntegerField(default=0),
        ),
    ]
