# Generated by Django 2.0.6 on 2018-06-23 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_job_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Workplace'),
        ),
    ]
