# Generated by Django 2.0.6 on 2018-06-23 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_shift_workplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('complete', models.BooleanField(default=False)),
                ('workplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Workplace')),
            ],
        ),
        migrations.RemoveField(
            model_name='shift',
            name='week',
        ),
        migrations.AddField(
            model_name='shift',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Employee'),
        ),
        migrations.AddField(
            model_name='shift',
            name='work_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.WorkWeek'),
        ),
    ]
