# Generated by Django 2.0.6 on 2018-06-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20180623_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='week',
            field=models.IntegerField(default=1),
        ),
    ]
